# Generated by Django 5.1.2 on 2024-11-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='room',
            field=models.CharField(default='Studio 1', help_text='Nama atau nomor ruangan.', max_length=100),
            preserve_default=False,
        ),
    ]
