# Generated by Django 5.1.2 on 2024-11-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0002_fitnessclass_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='room',
            field=models.CharField(choices=[('Studio 1', 'Studio 1'), ('Studio 2', 'Studio 2'), ('Studio 3', 'Studio 3'), ('Studio 4', 'Studio 4'), ('Studio 5', 'Studio 5')], max_length=100),
        ),
    ]
